# 01- how to find the version

In [1]:
import pandas as pd 
pd.__version__

'2.3.3'

In [3]:
# another way
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : 9c8bc3e55188c8aff37207a74f1dd144980b8874
python                : 3.14.0
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.26200
machine               : AMD64
processor             : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252

pandas                : 2.3.3
numpy                 : 2.4.0
pytz                  : 2025.2
dateutil              : 2.9.0.post0
pip                   : 25.2
Cython                : None
sphinx                : None
IPython               : 9.8.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : 3.10.8
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2025.3
qtpy                  : None
pyqt5                 : None

# 02. Make a dataframe

In [7]:
df=pd.DataFrame({'A colum': [1,2,3,6,4],'B colum':[4,5,6,7,8]})
df

   A colum  B colum
0        1        4
1        2        5
2        3        6
3        6        7
4        4        8

In [10]:
# numpy array use to create dataframe
import numpy as np
arr= np.array([[1,2,3], [4,5,6], [7,8,9]])
pd.DataFrame(arr)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [11]:
# numpy array dataframe
pd.DataFrame(np.random.rand(4,8))

,0,1,2,3,4,5,6,7
0,0.697887,0.764954,0.380577,0.188787,0.275257,0.402740,0.939970,0.425410
1,0.208628,0.732620,0.836305,0.861084,0.441699,0.171537,0.488308,0.841099
2,0.888371,0.286033,0.844636,0.990301,0.349664,0.871484,0.111533,0.777739
3,0.117305,0.355606,0.256733,0.160094,0.063417,0.108356,0.733372,0.421407

In [22]:
pd.DataFrame(np.random.rand(4,8), columns=list("ABCDEFGi"))

,A,B,C,D,E,F,G,i
0,0.119818,0.840913,0.906604,0.199070,0.537987,0.470735,0.046145,0.331865
1,0.850899,0.721477,0.064324,0.095352,0.418875,0.208919,0.412879,0.850556
2,0.737852,0.147653,0.085804,0.884145,0.026034,0.555141,0.622970,0.543023
3,0.147437,0.248371,0.060500,0.131180,0.911818,0.363696,0.015646,0.839585

# how to rename a colum

In [20]:
import seaborn as sns
df= sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True